spring.application.name=hotel

spring.datasource.url=jdbc:postgresql://localhost:5433/hotel_db
spring.datasource.username=admin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=5e0a5e982b25be
spring.mail.password=2a3b633a286bb3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true